version: '3'

services:
  nginx:
    container_name: 'www.example.com'
    build: ./dockerfiles/nginx
    image: 'centos-ssh-nginx:1.0'
    restart: always
    hostname: 'www.example.com'
    privileged: true
    ports:
        - '2023:22'
        - '80:80'
    environment: 
          SSH_USER: root
          # sudo 免密码
          SSH_SUDO: ALL=(ALL) NOPASSWD:ALL
          SSH_USER_PASSWORD: Passw0rd!
          SSH_PASSWORD_AUTHENTICATION: 'true'
          SSH_AUTHORIZED_KEYS: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDkXTtMSy4D6L1TPwHZxd1EXjjVWDC/93CvtlbS7PTmlHdQFbCttgPoZp7mmwfdNanI1x6fOiAKBBaX6mEZyfcYMa3ZfZw+lU+N2n0slknoEcTxmGqG9rIy0uk9NEYN/zxunK6xVufvwhggKSAAQDMEMNqyxat2JJJ/Wn2GPlOEJtYIWC+al+gtVqya5Nszs6T/1OjZ0hP6KKVeMBxDl0tmU6CIMiMHhTcGK4u6uG2wuK1nDFWZreJYgQOKobUCNiBTiVSwMp7NpobytdX3KLCfeoDM2DSKMlQVDYIav5VEWSFb7t51YTQKeCEkNHwVMX5jCmqF8IbYr7N5fRwt5xDz victoryw@CNvictoryw-2.local
  mysql:
    image: 'mysql'
    container_name: 'mysql.demo'
    restart: always
    ports:
      - '13306:3306'
    cap_add:
      - SYS_NICE  
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    