version: '3.9'

services:
  nginx:
    container_name: 'www.example.com'
    build: ./dockerfiles/nginx
    image: 'centos-ssh-nginx:1.0'
    restart: always
    hostname: 'www.example.com'
    privileged: true
    ports:
        - '2023:22'
        - '80:80'
    environment: 
          SSH_USER: root
          # sudo 免密码
          SSH_SUDO: ALL=(ALL) NOPASSWD:ALL
          SSH_USER_PASSWORD: Passw0rd!
          SSH_PASSWORD_AUTHENTICATION: 'true'
          # this public key is from ./ssh-key/id_rsa_shared.pub
          SSH_AUTHORIZED_KEYS: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC4ee2r0EY5vLX3A1KzDc3esC7GpfpzzVMUtpcOuryfFFu30wNNy79M31mD4QjL7/quc/O1PYKknFqkCkSvJJwS1tTHmfWL7s2G4lNjjblbzdPC2RigwAVHUlZonNOE9xmNX1yDg55LRD5aFQID89kEX395fmloq07mOwQ/YwP65JaXGbaTUv2+vz133vLi7Ri44ggRyod5C9DWwEr1Gk+pGupjs/OF3Npfdcuh0hMEUM+WDK/jsqeFQBjFJ3o+WOS++5mT0Q7nS35AYZ/iPZBDexUl/T+sUvQBtM2aC6LHMRMRryvMrn6v6/bzs+M2VKtYOzc6z2SLCc+2g8b4ffFNH4ol7lunOHUJPA6Ga5Y4QrIaNnYlwcVfdH8ONb6j7Ba+S8tFZz06fCKBEFs8HvHBhkbLbLofCI+oIxBcvrWm2YcAdWSDxG8zrTiCY1IGK638h1Xph8SMX0FWEycMSXPAzOLloze9NMZ9fnUmId8CV0NjW6fdvZqxk/asNzZmM+GyaizdxpravgxwCq5ZybaJZ1vlD+29QVwH9W+ngatGxrHZ7W2g8apDCtCM+DDrCId0Csue70GfDYQavTmbrvEONZP162TvSvMnSLvJ+IZyj53JL79sZWcj8ib7Gg2YxWphVGCY/2OYJWHpoB7S8Fw3dUYhQ7NCN9Dsz0zMrM0hiQ== yanwang@Yans-MacBook-Pro.local
    networks:
        - auto-deployment-demo
  mysql:
    image: 'mysql'
    container_name: 'mysql.demo'
    restart: always
    ports:
      - '13306:3306'
    cap_add:
      - SYS_NICE  
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: demo
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    networks:
        - auto-deployment-demo
  jenkins:
      build: ./dockerfiles/jenkins
      image: 'jenkins-ssh'
      container_name: jenkins
      restart: always
      privileged: true
      user: root
      ports:
        - 8080:8080
        - 50000:50000
      volumes:
        -  /var/run/docker.sock:/var/run/docker.sock  #run container in the host 
      networks:
        - auto-deployment-demo
networks:
  auto-deployment-demo:
    name: auto-deployment-demo
    