FROM jenkins/jenkins:lts-jdk11
USER root
RUN apt-get update && apt-get install -y openssh-client && apt-get install -y curl

# Install docker client    
ENV DOCKER_CHANNEL stable
ENV DOCKER_VERSION 17.03.1-ce
ENV DOCKER_API_VERSION 1.27
RUN curl -fsSL "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/x86_64/docker-${DOCKER_VERSION}.tgz" \
  | tar -xzC /usr/local/bin --strip=1 docker/docker

RUN mkdir /root/.ssh
# The id_rsa_shard file from the ../../ssh-key/id_rsa_shared
COPY id_rsa_shared /root/.ssh/id_rsa
COPY ssh_config /root/.ssh/config
RUN chown -R root:root root/.ssh

ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"  
