---
- hosts: ci
  tasks:
    - name: deploy new release app
      community.docker.docker_container:
        name: app-v1
        image: demo-app:1.0
        detach: yes
        state: started
        restart: true
        ports:
          - "{{app_port}}:3000"
        env:
          DBHost: "{{db_host}}"  
          DBUser: "{{db_user}}"
          DBPasswrod: "{{db_password}}"
          DB: "{{db_name}}"
          DBPort: "{{db_port}}"

        networks:
          - name: auto-deployment-demo
      register: command_output

    - debug:
        var: command_output.container.Id
- hosts: ci
  tasks:
    - name: smoke test
      uri:
        url: "{{ app_smoke_test_url }}"
        return_content: yes
        status_code: 200
      register: response
      failed_when: response.content != "[{\"id\":1,\"title\":\"Demo\"}]"
    
    - debug:
        var: response
