---
- hosts: appserver
  tasks:
    - name: destroy release app
      shell: >
        docker rm -f app-v1 2>/dev/null || true
    - name: deploy new release app
      shell: >
        docker run 
        -p 13000:{{app_port}} 
        -e DBHost={{db_host}} 
        -e DBPort={{db_port}} 
        -e DBUser={{db_user}} 
        -e DBPasswrod={{ db_password }} 
        -e DB={{ db_name }} 
        --name app-v1
        --network=auto-deployment-demo
        -d  
        demo-app:1.0
      register: command_output

    - debug:
        var: command_output.stdout_lines
- hosts: ci
  tasks:
    - name: smoke test
      uri:
        url: http://app-v1:3000/demo
        return_content: yes
        status_code: 200
      register: response
      failed_when: response.content != "[{\"id\":1,\"title\":\"Demo\"}]"
    
    - debug:
        var: response
