---
- hosts: appserver
  tasks:
    - name: destroy release app
      shell: >
        docker rm app-v1 -f
    - name: deploy new release app
      shell: >
        docker run 
        -p {{app_port}}:3000 
        -e DBHost={{db_host}} 
        -e DBPort={{db_port}} 
        -e DBUser={{db_user}} 
        -e DBPasswrod={{ db_password }} 
        -e DB={{ db_name }} 
        --name app-v1
        --networks: auto-deployment-demo
        -d  
        demo-app:1.0
      register: command_output

    - debug:
        var: command_output.stdout_lines

    - name: smoke test
      uri:
        url: http://localhost:13000/demo
        return_content: yes
        status_code: 200
      register: response
      failed_when: response.content != "[{\"id\":1,\"title\":\"Demo\"}]"
    
    - debug:
        var: response
