---
- hosts: ci
  tasks:
    - name: migration demo database
      shell: docker run --networks:auto-deployment-demo --rm db-migration:1.0 -url=jdbc:mysql://{{ db_host }}:{{db_port}}/{{db_name}} -user={{ db_user }} -password={{db_password}} migrate
      register: command_output

    - debug:
        var: command_output.stdout_lines
