---
- hosts: lbserver
  tasks:
    - name: replace nginx config
      become: yes
      template:
        src: ./templates/nginx/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        mode: '0644'
        backup: yes
      notify: reload nginx config
    
    - name: Flush handlers
      meta: flush_handlers

  handlers: 
    - name: reload nginx config
      command: nginx -s reload


- hosts: ci
  tasks:
    - name: smoke test
      uri:
        url: "{{ service_url }}"
        return_content: yes
        status_code: 200
      register: response
      failed_when: response.content != "[{\"id\":1,\"title\":\"Demo\"}]"
    
    - debug:
        var: response
    
    

