FROM node:21 As Builder
WORKDIR /root/app
COPY package.json .
RUN npm install

FROM node:21 As Release
WORKDIR /root
COPY --from=builder /root/app/node_modules ./node_modules
COPY . .
EXPOSE 3000
CMD node server.js



